-- FISIOCAREHUB SUPABASE SETUP SCRIPT
-- Execute este script no SQL Editor do seu projeto Supabase para garantir que todas as tabelas e buckets existam.

-- 1. Tabelas Principais
CREATE TABLE IF NOT EXISTS public.perfis (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    nome_completo TEXT,
    email TEXT,
    telefone TEXT,
    bio TEXT,
    avatar_url TEXT,
    tipo_usuario TEXT DEFAULT 'paciente', -- 'paciente' ou 'fisioterapeuta'
    plano TEXT DEFAULT 'free', -- 'free', 'fisioterapeuta', 'admin'
    crefito TEXT,
    especialidade TEXT,
    localizacao TEXT,
    endereco TEXT,
    cep TEXT,
    pais TEXT DEFAULT 'Brasil',
    genero TEXT,
    tipo_servico TEXT, -- 'domicilio', 'online', 'ambos'
    is_pro BOOLEAN DEFAULT false,
    aprovado BOOLEAN DEFAULT false,
    status_aprovacao TEXT DEFAULT 'pendente',
    documentos TEXT[] DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.triagens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id UUID REFERENCES public.perfis(id) ON DELETE CASCADE NOT NULL,
    idade INTEGER,
    sexo TEXT,
    peso NUMERIC,
    altura NUMERIC,
    profissao TEXT,
    atividade_fisica TEXT,
    regiao_dor TEXT,
    inicio_sintomas TEXT,
    tempo_sintomas TEXT,
    historico_clinico JSONB, -- Armazena {fisioterapia_anterior: boolean, diagnostico_medico: boolean, exames_imagem: string[]}
    doencas_preexistentes TEXT[] DEFAULT '{}',
    escala_dor INTEGER,
    limitacao_funcional TEXT, -- 'leve', 'moderada', 'grave'
    red_flag BOOLEAN DEFAULT false,
    classificacao TEXT, -- 'musculoesquelético', 'neurológico', etc.
    gravidade TEXT, -- 'leve', 'moderado', 'grave'
    relatorio TEXT,
    status TEXT DEFAULT 'pendente',
    data_triagem TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    ai_analysis JSONB, -- Legado ou para dados extras da IA
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.prontuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id UUID NOT NULL, -- Can be from perfis or pacientes
    fisio_id UUID REFERENCES public.perfis(id) ON DELETE CASCADE NOT NULL,
    data_registro TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    conteudo JSONB NOT NULL, -- Armazena {text: string, attachments: string[]}
    tipo_atendimento TEXT,
    evolucao TEXT,
    attachments TEXT[] DEFAULT '{}', -- Legado ou redundante
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.agendamentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id UUID NOT NULL, -- Can be from perfis or pacientes
    fisio_id UUID REFERENCES public.perfis(id) ON DELETE CASCADE NOT NULL,
    data_hora TIMESTAMP WITH TIME ZONE, -- Legado
    data_servico TIMESTAMP WITH TIME ZONE NOT NULL, -- Usado no app
    status TEXT DEFAULT 'pendente', -- 'pendente', 'confirmado', 'cancelado', 'concluido'
    tipo TEXT DEFAULT 'online', -- 'online', 'presencial'
    servico TEXT, -- Usado no app
    observacoes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.notificacoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.perfis(id) ON DELETE CASCADE NOT NULL,
    titulo TEXT NOT NULL,
    mensagem TEXT NOT NULL,
    lida BOOLEAN DEFAULT false,
    link TEXT,
    tipo TEXT DEFAULT 'info',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.mensagens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    remetente_id UUID REFERENCES public.perfis(id) ON DELETE CASCADE NOT NULL,
    destinatario_id UUID REFERENCES public.perfis(id) ON DELETE CASCADE NOT NULL,
    conteudo TEXT NOT NULL,
    data_envio TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    lida BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.pacientes (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    fisioterapeuta_id UUID REFERENCES public.perfis(id) ON DELETE CASCADE NOT NULL,
    nome TEXT NOT NULL,
    telefone TEXT,
    email TEXT,
    data_nascimento DATE,
    endereco TEXT,
    diagnostico TEXT,
    observacoes TEXT,
    foto_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.atendimentos (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    paciente_id UUID REFERENCES public.pacientes(id) ON DELETE CASCADE NOT NULL,
    fisioterapeuta_id UUID REFERENCES public.perfis(id) ON DELETE CASCADE NOT NULL,
    data DATE NOT NULL,
    hora TIME NOT NULL,
    tipo TEXT DEFAULT 'Presencial', -- 'Presencial', 'Online', 'Domiciliar'
    local TEXT,
    status TEXT DEFAULT 'agendado', -- 'agendado', 'realizado', 'cancelado'
    observacoes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.evolucoes (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    paciente_id UUID REFERENCES public.pacientes(id) ON DELETE CASCADE NOT NULL,
    atendimento_id UUID REFERENCES public.atendimentos(id) ON DELETE CASCADE NOT NULL,
    dor_escala INTEGER CHECK (dor_escala >= 0 AND dor_escala <= 10),
    descricao TEXT,
    exercicios_realizados TEXT,
    observacoes TEXT,
    plano TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.arquivos_paciente (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    paciente_id UUID REFERENCES public.pacientes(id) ON DELETE CASCADE NOT NULL,
    arquivo_url TEXT NOT NULL,
    tipo TEXT, -- 'Exame', 'Ressonância', 'Raio-X', 'Foto', 'Documento'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.exercicios_paciente (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    paciente_id UUID REFERENCES public.pacientes(id) ON DELETE CASCADE NOT NULL,
    exercicio_id UUID REFERENCES public.exercicios(id) ON DELETE CASCADE NOT NULL,
    observacoes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.exercicios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fisio_id UUID REFERENCES public.perfis(id) ON DELETE CASCADE,
    nome TEXT NOT NULL,
    descricao TEXT,
    series TEXT,
    repeticoes TEXT,
    video_url TEXT,
    imagem_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Habilitar RLS (Row Level Security)
ALTER TABLE public.perfis ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.triagens ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.prontuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.agendamentos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notificacoes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mensagens ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.exercicios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pacientes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.atendimentos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.evolucoes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.arquivos_paciente ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.exercicios_paciente ENABLE ROW LEVEL SECURITY;

-- 3. Políticas de Segurança (Exemplos Básicos)
-- Perfis: Usuários podem ler qualquer perfil, mas só editar o seu
CREATE POLICY "Perfis são legíveis por todos" ON public.perfis FOR SELECT USING (true);
CREATE POLICY "Usuários podem editar o próprio perfil" ON public.perfis FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Usuários podem inserir o próprio perfil" ON public.perfis FOR INSERT WITH CHECK (auth.uid() = id);

-- Pacientes: Fisios veem seus pacientes
CREATE POLICY "Fisios veem seus pacientes" ON public.pacientes FOR SELECT USING (auth.uid() = fisioterapeuta_id);
CREATE POLICY "Fisios gerenciam seus pacientes" ON public.pacientes FOR ALL USING (auth.uid() = fisioterapeuta_id);

-- Agendamentos: Fisios gerenciam seus agendamentos
CREATE POLICY "Fisios gerenciam seus agendamentos" ON public.agendamentos FOR ALL USING (auth.uid() = fisio_id);

-- Evoluções: Fisios gerenciam evoluções de seus pacientes
CREATE POLICY "Fisios gerenciam evoluções" ON public.evolucoes FOR ALL USING (
    EXISTS (SELECT 1 FROM public.pacientes WHERE id = paciente_id AND fisioterapeuta_id = auth.uid())
);

-- Arquivos: Fisios gerenciam arquivos de seus pacientes
CREATE POLICY "Fisios gerenciam arquivos" ON public.arquivos_paciente FOR ALL USING (
    EXISTS (SELECT 1 FROM public.pacientes WHERE id = paciente_id AND fisioterapeuta_id = auth.uid())
);

-- Prescrições: Fisios gerenciam prescrições de seus pacientes
CREATE POLICY "Fisios gerenciam prescrições" ON public.exercicios_paciente FOR ALL USING (
    EXISTS (SELECT 1 FROM public.pacientes WHERE id = paciente_id AND fisioterapeuta_id = auth.uid())
);

-- Exercícios: Todos podem ler, apenas fisios podem criar/editar
CREATE POLICY "Exercícios são legíveis por todos" ON public.exercicios FOR SELECT USING (true);
CREATE POLICY "Fisios podem gerenciar exercícios" ON public.exercicios FOR ALL USING (
    EXISTS (SELECT 1 FROM public.perfis WHERE id = auth.uid() AND tipo_usuario = 'fisioterapeuta')
);

-- Triagens: Pacientes veem as suas, fisios veem de todos
CREATE POLICY "Pacientes veem suas triagens" ON public.triagens FOR SELECT USING (auth.uid() = paciente_id);
CREATE POLICY "Fisios veem todas as triagens" ON public.triagens FOR SELECT USING (
    EXISTS (SELECT 1 FROM public.perfis WHERE id = auth.uid() AND tipo_usuario = 'fisioterapeuta')
);
CREATE POLICY "Pacientes inserem triagens" ON public.triagens FOR INSERT WITH CHECK (auth.uid() = paciente_id);

-- Mensagens: Usuários veem mensagens onde são remetentes ou destinatários
CREATE POLICY "Usuários veem suas mensagens" ON public.mensagens FOR SELECT USING (auth.uid() = remetente_id OR auth.uid() = destinatario_id);
CREATE POLICY "Usuários enviam mensagens" ON public.mensagens FOR INSERT WITH CHECK (auth.uid() = remetente_id);

-- 4. Buckets de Storage
-- Nota: Buckets devem ser criados via Dashboard ou API de Storage
-- Buckets sugeridos: 'avatars' (público), 'documents' (privado)

-- 5. Funções Auxiliares (Opcional)
-- Função para atualizar updated_at automaticamente
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_updated_at
BEFORE UPDATE ON public.perfis
FOR EACH ROW
EXECUTE FUNCTION public.handle_updated_at();
