import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const cors={ "Access-Control-Allow-Origin":"*", "Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type" };
const url=Deno.env.get("SUPABASE_URL")!, key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!, resend=Deno.env.get("RESEND_API_KEY")!;
const from=Deno.env.get("RESEND_FROM")||"FisioCareHub <onboarding@resend.dev>";
const out=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{...cors,"Content-Type":"application/json"}});
const esc=(s:string)=>s.replace(/[&<>"']/g,(c)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]||c));
async function db(path:string,opt:RequestInit={}){return fetch(`${url}/rest/v1/${path}`,{...opt,headers:{apikey:key,Authorization:`Bearer ${key}`,"Content-Type":"application/json",...(opt.headers||{})}})}
async function admin(token:string){const u=await fetch(`${url}/auth/v1/user`,{headers:{apikey:key,Authorization:`Bearer ${token}`}});if(!u.ok)return null;const user=await u.json();const p=await db(`perfis?id=eq.${encodeURIComponent(user.id)}&select=id,tipo_usuario`);const rows=await p.json();return rows[0]?.tipo_usuario==="admin"?user:null}
function personalize(value:string,name:string){return value.replace(/\{\{nome\}\}/gi,name||"Olá");}
async function email(to:string,sub:string,msg:string,link:string|null,ctaLabel:string,name:string){
  const personalizedMessage=personalize(msg,name);
  const personalizedSubject=personalize(sub,name);
  const body=personalizedMessage.split(/\n\s*\n/).map(p=>`<p style="margin:0 0 18px;color:#cbd5e1;font:15px/25px Arial,sans-serif;">${esc(p).replace(/\n/g,"<br>")}</p>`).join("");
  const cta=link?`<div style="text-align:center;margin:28px 0 8px"><a href="${esc(link)}" style="display:inline-block;padding:14px 24px;background:#22d3ee;color:#06101f;text-decoration:none;border-radius:12px;font:bold 14px Arial,sans-serif;box-shadow:0 8px 24px rgba(34,211,238,.18)">${esc(ctaLabel||"Acessar FisioCareHub")}</a></div>`:"";
  const html=`<!doctype html><html><body style="margin:0;background:#020817;padding:24px 12px"><div style="max-width:620px;margin:0 auto;background:#071525;border:1px solid #19314d;border-radius:22px;overflow:hidden"><div style="padding:25px 30px;background:#06101f;border-bottom:1px solid #19314d"><div style="font:bold 23px Arial,sans-serif;color:#fff">Fisio<span style="color:#22d3ee">CareHub</span></div><div style="margin-top:7px;font:11px Arial,sans-serif;color:#64748b;letter-spacing:1.5px;text-transform:uppercase">Experiência digital em fisioterapia</div></div><div style="padding:30px">${body}${cta}</div><div style="padding:18px 30px;background:#06101f;border-top:1px solid #19314d;font:11px/18px Arial,sans-serif;color:#64748b">Mensagem enviada pelo FisioCareHub.</div></div></body></html>`;
  const r=await fetch("https://api.resend.com/emails",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${resend}`},body:JSON.stringify({from,to:[to],subject:personalizedSubject,html})});
  if(!r.ok)throw new Error(await r.text());
}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return out({error:"Método não permitido"},405);try{
  const token=(req.headers.get("Authorization")||"").replace(/^Bearer\s+/i,"");const a=await admin(token);if(!a)return out({error:"Acesso restrito ao administrador."},403);
  const p=await req.json();const title=String(p.title||"").trim(),subject=String(p.subject||"").trim(),message=String(p.message||"").trim(),link=p.link?String(p.link).trim():null,ctaLabel=String(p.ctaLabel||"Acessar FisioCareHub").trim(),target=String(p.targetAudience||"fisioterapeutas"),se=p.sendEmail!==false,si=p.sendInApp!==false;
  if(!title||!subject||!message)return out({error:"Título, assunto e mensagem são obrigatórios."},400);
  let filter="tipo_usuario=neq.admin";if(target==="fisioterapeutas")filter="tipo_usuario=eq.fisioterapeuta";if(target==="pacientes")filter="tipo_usuario=eq.paciente";if(target==="pro")filter="tipo_usuario=neq.admin&or=(is_pro.eq.true,plan_type.eq.pro)";if(target==="free")filter="tipo_usuario=neq.admin&is_pro=eq.false&plan_type=neq.pro";
  const pr=await db(`perfis?${filter}&select=id,nome_completo,email,tipo_usuario&order=created_at.desc`);if(!pr.ok)throw new Error(await pr.text());const profiles=await pr.json();
  const cr=await db("marketing_campaigns",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({title,subject,message,link,send_email:se,send_in_app:si,target_audience:target,created_by:a.id,status:"sending"})});if(!cr.ok)throw new Error(await cr.text());const campaign=(await cr.json())[0];
  let sent=0,failed=0;const rows:any[]=[];
  for(const u of profiles){const name=String(u.nome_completo||"").trim().split(/\s+/)[0]||"";const personalizedMessage=personalize(message,name);if(si){const n=await db("notificacoes",{method:"POST",headers:{Prefer:"return=minimal"},body:JSON.stringify({user_id:u.id,titulo:personalize(title,name),mensagem:personalizedMessage,tipo:"marketing",link,metadata:{campaign_id:campaign.id,marketing:true,cta_label:ctaLabel},lida:false})});const ok=n.ok;rows.push({campaign_id:campaign.id,user_id:u.id,channel:"in_app",status:ok?"sent":"failed",error_message:ok?null:await n.text(),sent_at:ok?new Date().toISOString():null});ok?sent++:failed++}if(se&&u.email){try{await email(u.email,subject,message,link,ctaLabel,name);rows.push({campaign_id:campaign.id,user_id:u.id,email:u.email,channel:"email",status:"sent",sent_at:new Date().toISOString()});sent++}catch(e){failed++;rows.push({campaign_id:campaign.id,user_id:u.id,email:u.email,channel:"email",status:"failed",error_message:String(e)})}}}
  if(rows.length)await db("marketing_campaign_recipients",{method:"POST",headers:{Prefer:"return=minimal"},body:JSON.stringify(rows)});const status=failed===0?"sent":sent>0?"partial":"failed";await db(`marketing_campaigns?id=eq.${campaign.id}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({status,total_recipients:rows.length,sent_count:sent,failed_count:failed,sent_at:new Date().toISOString()})});return out({success:true,campaignId:campaign.id,audienceCount:profiles.length,totalRecipients:rows.length,sentCount:sent,failedCount:failed,status})
}catch(e){console.error(e);return out({error:e instanceof Error?e.message:String(e)},500)}});